[package]
name = "lrwn"
version = "1.0.0"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
hex = "0.4"
cmac = "0.6"
aes = "0.7"
serde = { version = "1.0", features = ["derive"] }
diesel = { version = "1.4", features = [ "postgres" ] }
chirpstack_api = { path = "../api/rust" }

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Misc
lazy_static = "1.4"
